name: UP OV Fi
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  update-ovpn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Remove Old OVPN Files
        run: |
          rm -f *.ovpn
      - name: Download New OVPN Files
        run: |
          wget -r -np -nH --cut-dirs=3 -A "*.ovpn" https://github.com/mudachyo/proxy-list/raw/master/vpn/
          mv vpn/*.ovpn .
          rm -rf vpn
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.ovpn
          git commit -m "به‌روزرسانی فایل‌های OVPN - $(date +'%Y-%m-%d')" || echo "هیچ تغییری برای کامیت وجود ندارد"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
