name: UP OV Fi
on:
  schedule:
    - cron: '0 0 * * *' # هر روز ساعت 00:00 UTC اجرا می‌شه (هر 24 ساعت)
  workflow_dispatch: { } # امکان اجرای دستی هم داره
jobs:
  update-ovpn:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه نوشتن در مخزن رو می‌ده
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # مخزن شما رو چک‌اوت می‌کنه
      - name: Remove Old OVPN Files
        run: |
          rm -f *.ovpn # فایل‌های قبلی .ovpn رو حذف می‌کنه
      - name: Download New OVPN Files
        run: |
          # دانلود همه فایل‌های .ovpn از شاخه vpn مخزن mudachyo/proxy-list
          wget -r -np -nH --cut-dirs=3 -A "*.ovpn" https://github.com/mudachyo/proxy-list/raw/master/vpn/
          # انتقال فایل‌ها از پوشه vpn به ریشه مخزن
          mv vpn/*.ovpn .
          # حذف پوشه موقتی vpn
          rm -rf vpn
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.ovpn
          git commit -m "به‌روزرسانی فایل‌های OVPN - $(date +'%Y-%m-%d')" || echo "هیچ تغییری برای کامیت وجود ندارد"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
